### ISSUE TITLE
DiscordSRV issue

### ISSUE THREAD

**Issue by RhinoCD** [quantiom/AdvancedVanish#16]
When I leave the server Not in vanish, it doesn't send the left the server message.

However everything else works:
When I join the server (Vanish automatically on) it doesn't send the message until I go out of vanish which is good,
When I go back in and out of vanish, it sends the left and join message just fine.

But when I leave the server not even in vanish, it doesn't send the leave message.

**Comment by quantiom** [comment]
This should not be the case. The only thing that the DiscordSRV hook does is send its own join and leave messages, not intercept existing ones. Could you try disabling the hook in the config and see if the issue still persists? It may be something to do with your DiscordSRV configuration.

**Comment by RhinoCD** [comment]
Ah fixed it, thank you!

**Comment by RhinoCD** [comment]
actaully nvm

**Comment by RhinoCD** [comment]
when I leave while in vanish, it now sends a left the server, than sends another one when I actually leave the server

**Comment by quantiom** [comment]
So when you vanish, it sends a leave message, and then when you actually leave, it sends another one?

**Comment by RhinoCD** [comment]
yes
