### ISSUE TITLE
Vanished Players are not removed from the tab list even when ProtocolLib is installed

### ISSUE THREAD

**Issue by Cyranos** [quantiom/AdvancedVanish#19]
As per the title I have both Advanced Vanish & ProtocolLib installed.

I am using the lastest paper version,
Version v1.2.2 Of Advanced Vanish,
And Version 5.0.0-SNAPSHOT-b600 of ProtocolLib

**Comment by quantiom** [comment]
Hi, which plugin are you using to handle/format the tab list? I don't believe I ever added a hook for any plugins that do that. The ProtocolLib hides players from the server list, which is the one that is in the server browser. However, I can most likely add a hook for the plugin you're using.

**Comment by quantiom** [comment]
Closed due to inactivity.
