### ISSUE TITLE
All join messages are blocked

### ISSUE THREAD

**Issue by PhoenixZTT** [quantiom/AdvancedVanish#2]
While enabled, all join messages even from normal players are blocked

<img width="607" alt="Screen Shot 2022-05-14 at 1 29 25 AM" src="https://user-images.githubusercontent.com/97313380/168417808-8f80b697-7da7-4707-8864-1cc3bd41409a.png">

**Comment by PhoenixZTT** [comment]
https://github.com/quantiom/AdvancedVanish/pull/3/commits/712a106a707902e14c589204dcb5378270e29112

**Comment by quantiom** [comment]
Fixed, thank you.
