### ISSUE TITLE
Vanished players not added to the vanishedPlayers list while using the AdvancedVanishAPI

### ISSUE THREAD

**Issue by TheSheepGoesBa** [quantiom/AdvancedVanish#22]
When using the AdvancedVanishAPI in Java, using any method to access the vanishedPlayers list(getVanishedPlayer(), isPlayerVanished()) does not return any vanished players. It always returns a list with a length of zero, causing isPlayerVanished() to always be false.

**Comment by quantiom** [comment]
This is very unlikely to be happening with just calls to `getVanishedPlayers` and `isPlayerVanished`, the whole plugin would not work correctly if these two methods did not return the correct values. Could you please show me how you are calling them? Thanks.

**Comment by TheSheepGoesBa** [comment]
I'm calling it using this code: `AdvancedVanishAPI.INSTANCE.getVanishedPlayers()`. I found it weird that I had to use `AdvancedVanishAPI.INSTANCE` to call anything in the API rather than just `AdvancedVanishAPI.method`. I followed all of the instructions to install it on the wiki.

**Comment by quantiom** [comment]
You need to use `AdvancedVanishAPI.INSTANCE` because it is a Kotlin object and you are accessing it in Java, that is fine though (assuming that you have `depend: [AdvancedVanish]` in your plugin.yml. Could you please use /vanish and then show the output of `AdvancedVanishAPI.INSTANCE.getVanishedPlayers().size()`?

**Comment by TheSheepGoesBa** [comment]
I see, that makes sense. `AdvancedVanishAPI.INSTANCE.getVanishedPlayers().size()` always outputs `0` no matter if I am in vanish or not. I am using `softdepend: [AdvancedVanish]` but I don't think that should be an issue.

**Comment by quantiom** [comment]
The problem was that he was shading the whole AdvancedVanish plugin into his plugin, so he was accessing a different instance of it. Closing this as completed now.
