### ISSUE TITLE
Please add support for interactive chat discordsrv

### ISSUE THREAD

**Issue by RhinoCD** [quantiom/AdvancedVanish#24]
I tried asking them to support advanced vanish but they said for advanced vanish to support interactive chat discordsrv using meta (no idea what that means but heres the ss) - The interactive chat discordsrv addon adds the ability for players to do /playerlist in discord to shoow the list of players who are in-game. Due to this, it also shows vanished players, and would be amazing if vanish could be supported.

https://gyazo.com/7cd42c38edda21bf1bc458546662ab36

link to plugin:
https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/

**Comment by quantiom** [comment]
This should be fixed in v1.2.5
