### ISSUE TITLE
Plugins can't hook into Advanced Vanish

### ISSUE THREAD

**Issue by RhinoCD** [quantiom/AdvancedVanish#25]
Pinata Party takes the MetaData value of "vanished" to see if a player is vanished or not from vanish plugins.
According to the developer, advanced vanish can't be used due to this.

"The plugin needs to set the players metadata value of "vanished" to true like every other vanish plugin does and its a universal thing that everyone does"

**Comment by quantiom** [comment]
The latest version, [v1.2.5](https://github.com/quantiom/AdvancedVanish/releases/tag/v1.2.5) does do this (https://github.com/quantiom/AdvancedVanish/blob/main/src/main/kotlin/me/quantiom/advancedvanish/util/AdvancedVanishAPI.kt#L42-L43). Please make sure you're using it and see if the issue still persists.

**Comment by RhinoCD** [comment]
I'm currently using version v1.2.5

[21:17:12 INFO]: AdvancedVanish version 1.2.5
[21:17:12 INFO]: A fully customizable and advanced vanish plugin.
[21:17:12 INFO]: Author: quantiom

**Comment by quantiom** [comment]
You'll need to make sure with the developer of that plugin that the metadata is being checked correctly then because it's definitely being set. I sent the line of code where it happens.

**Comment by RhinoCD** [comment]
![image](https://user-images.githubusercontent.com/78483451/224905298-c65394cc-7b3d-462b-a909-eaba4c1fa0b7.png)

**Comment by quantiom** [comment]
Yeah, that seems like it should work. I even decompiled the latest release on GitHub just to make sure it's there: 
![image](https://user-images.githubusercontent.com/35455461/225060332-81acc003-0c0a-4876-95fd-ef7455e2d04e.png)
