### ISSUE TITLE
Question: Do players actually vanish?

### ISSUE THREAD

**Issue by Jannik44** [quantiom/AdvancedVanish#34]
Looks like i only get effects along a few other things, but can players with player-esp cheats enabled still see me? or am i just invisible for vanilla players? this would be a very critical flaw

**Comment by quantiom** [comment]
The invisibility effect is just an extra feature - kind of to show you that you are vanished. Players that do not have permission to see you, cheats or not, will not be able to see you at all. None of your movement or similar packets will be sent to them.
