### ISSUE TITLE
[Bug] Vanished users can be messaged.

### ISSUE THREAD

**Issue by ItzSave** [quantiom/AdvancedVanish#4]
When a user is in vanish they can still be private messaged which makes the vanished status pointless.

Version: 1.18.2
Related Plugins: Essentials, VentureChat
AdvancedVanish Version: 1.1.3

**Comment by quantiom** [comment]
Hi, I could not reproduce this with the VentureChat plugin.

When vanished:
![image](https://user-images.githubusercontent.com/35455461/169152954-6d65a0b0-3fdc-4551-8eb4-13db9f4f10dc.png)

When not vanished:
![image](https://user-images.githubusercontent.com/35455461/169152971-0eefd2a6-fd1e-4bea-9658-b81608aedbcc.png)

**Comment by ItzSave** [comment]
The problem is /msg <username>. When in a vanished state users can still do that to message them and see if they are online or not.

**Comment by ItzSave** [comment]
To recreate:

- Enter /vanish on an account.
- Have another account without permission to see vanished users.
- The default account should use /msg "vanished player's name"

Expected Behavior:
- Default user should not be able to message the vanished users should return a user is offline message.

**Comment by ItzSave** [comment]
Any further updates on this?

**Comment by quantiom** [comment]
I believe this is an issue with the VentureChat plugin. The if statement here only checks if the player is online instead of checking if the other player can see them (if they are in vanish): https://github.com/Aust1n46/VentureChat/blob/38746624d931365fa790b655b7caf6083bf9ba55/src/main/java/mineverse/Aust1n46/chat/listeners/ChatListener.java#L79.

**Comment by ItzSave** [comment]
Should I make an issue on their page and see what if anything can be done?

**Comment by quantiom** [comment]
Yes
