### ISSUE TITLE
Feature Request: Saving vanish state

### ISSUE THREAD

**Issue by GavvyDizzle** [quantiom/AdvancedVanish#7]
It would be helpful to have the plugin save if the player is in vanish or not. Currently, the plugin only allows you to specify on/off on join, instead of what you last were when you logged off.

**Comment by quantiom** [comment]
Added in v1.1.6 (c1dfaf2cdde5f0789c5d25e30de193eb9cabf0be)

**Comment by GavvyDizzle** [comment]
To add to this, it would be nice for the vanish state to persist outside of server restarts, meaning the data is saved outside of memory.
